version: '3.9'
services:
    email:
        image: 'maildev/maildev'
        ports:
            - '8082:1080'
        healthcheck:
            test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:1080/healthz || exit 1" ]
            interval: 5s
            timeout: 5s
            retries: 10

    db:
        image: 'postgres:14.5-alpine'
        environment:
            POSTGRES_DB: refueling
            POSTGRES_USER: refueling
            POSTGRES_PASSWORD: refueling123
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U refueling']
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - postgre_refueling_data:/var/lib/postgresql/data

    backend:
        image: 'refueling-log-backend:latest'
        restart: always
        ports:
            - '8080:8080'
        environment:
            PORT: 8080
            BASE_PATH: '/api'
            NODE_ENV: 'development'
            DATABASE_PASSWORD: refueling123
            DATABASE_USER: refueling
            DATABASE: refueling
            DATABASE_HOST: db
            DATABASE_PORT: 5432
            DATABASE_LOGGING: 'true'
            TOKEN_SIGN_KEY: somesecrettoken
            TOKEN_EXPIRES_IN: 5m
            REFRESH_TOKEN_EXPIRES_IN: 1h
            EMAIL_HOST: email
            EMAIL_PORT: 1025
            EMAIL_USER:
            EMAIL_PASS:
            EMAIL_FROM: email@email.email
            CONFIRM_URL: 'http://localhost:3000/confirm/'
            REGISTRATION_ENABLED: 'true'
        healthcheck:
            test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1" ]
            interval: 10s
            timeout: 5s
            retries: 10
        depends_on:
            db:
                condition: service_healthy
            email:
                condition: service_healthy

volumes:
    postgre_refueling_data:
    pgadmin_data:
