version: '3.9'
services:
    email:
        image: 'maildev/maildev'
        ports:
            - '8082:1080'
            - '1025:1025'
        healthcheck:
            test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:1080/healthz || exit 1" ]
            interval: 5s
            timeout: 5s
            retries: 10

    db:
        image: 'postgres:14.5-alpine'
        environment:
            POSTGRES_DB: refueling
            POSTGRES_USER: refueling
            POSTGRES_PASSWORD: refueling123
        ports:
            - '5432:5432'
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U refueling']
            interval: 5s
            timeout: 5s
            retries: 10
        volumes:
            - postgre_refueling_data:/var/lib/postgresql/data

volumes:
    postgre_refueling_data:
