version: '3.9'
services:
    email:
        image: 'maildev/maildev'
        ports:
            - '8082:1080'
            - '1025:1025'

    db:
        image: 'postgres:14.5-alpine'
        environment:
            POSTGRES_DB: refueling
            POSTGRES_USER: refueling
            POSTGRES_PASSWORD: refueling123
        ports:
            - '5432:5432'
        volumes:
            - postgre_refueling_data:/var/lib/postgresql/data

    pgadmin:
        image: 'dpage/pgadmin4'
        environment:
            PGADMIN_DEFAULT_EMAIL: email@email.email
            PGADMIN_DEFAULT_PASSWORD: refueling123
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            MASTER_PASSWORD_REQUIRED: 'False'
        ports:
            - '8083:80'
        volumes:
            - ../servers.json:/pgadmin4/servers.json
            - pgadmin_data:/var/lib/pgadmin
        depends_on:
            - db

volumes:
    postgre_refueling_data:
    pgadmin_data:
